baseURL = 'https://tangben.bot.cd'
locale = 'zh-CN'
title = 'My New Hugo Project'
theme = 'PaperMod'

[params]
  author = '唐奔'
  description = '博客描述'
  
[menu]
  [[menu.main]]
    name = '首页'
    url = '/'
    weight = 10
  [[menu.main]]
    name = '文章'
    url = '/posts/'
    weight = 20
